/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authenticatedSettingsRouteRouteImport } from './routes/(authenticated)/settings/route'
import { Route as authenticatedInsightsRouteRouteImport } from './routes/(authenticated)/insights/route'
import { Route as authenticatedConversationsRouteRouteImport } from './routes/(authenticated)/conversations/route'
import { Route as authenticatedSettingsIndexRouteImport } from './routes/(authenticated)/settings/index'
import { Route as authenticatedHelpCenterIndexRouteImport } from './routes/(authenticated)/help-center/index'
import { Route as authenticatedSettingsNotificationsRouteImport } from './routes/(authenticated)/settings/notifications'
import { Route as authenticatedSettingsDisplayRouteImport } from './routes/(authenticated)/settings/display'
import { Route as authenticatedSettingsAppearanceRouteImport } from './routes/(authenticated)/settings/appearance'
import { Route as authenticatedSettingsAccountRouteImport } from './routes/(authenticated)/settings/account'
import { Route as authenticatedMyNoobleShopRouteRouteImport } from './routes/(authenticated)/my-nooble/shop/route'
import { Route as authenticatedMyNoobleAgentsRouteRouteImport } from './routes/(authenticated)/my-nooble/agents/route'
import { Route as authenticatedMyNoobleShopIndexRouteImport } from './routes/(authenticated)/my-nooble/shop/index'
import { Route as authenticatedMyNoobleProfileIndexRouteImport } from './routes/(authenticated)/my-nooble/profile/index'
import { Route as authenticatedMyNoobleDesignIndexRouteImport } from './routes/(authenticated)/my-nooble/design/index'
import { Route as authenticatedMyNoobleAgentsIndexRouteImport } from './routes/(authenticated)/my-nooble/agents/index'
import { Route as authenticatedInsightsProfileAnalyticsIndexRouteImport } from './routes/(authenticated)/insights/profile-analytics/index'
import { Route as authenticatedInsightsOverviewIndexRouteImport } from './routes/(authenticated)/insights/overview/index'
import { Route as authenticatedInsightsConversationFlowIndexRouteImport } from './routes/(authenticated)/insights/conversation-flow/index'
import { Route as authenticatedMyNoobleShopOrdersIndexRouteImport } from './routes/(authenticated)/my-nooble/shop/orders/index'
import { Route as authenticatedMyNoobleShopMyProductsIndexRouteImport } from './routes/(authenticated)/my-nooble/shop/my-products/index'
import { Route as authenticatedMyNoobleShopEditIndexRouteImport } from './routes/(authenticated)/my-nooble/shop/edit/index'
import { Route as authenticatedMyNoobleAgentsToolsIndexRouteImport } from './routes/(authenticated)/my-nooble/agents/tools/index'
import { Route as authenticatedMyNoobleAgentsKnowledgeIndexRouteImport } from './routes/(authenticated)/my-nooble/agents/knowledge/index'
import { Route as authenticatedMyNoobleAgentsAgentsIndexRouteImport } from './routes/(authenticated)/my-nooble/agents/agents/index'

const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedSettingsRouteRoute =
  authenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedInsightsRouteRoute =
  authenticatedInsightsRouteRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedConversationsRouteRoute =
  authenticatedConversationsRouteRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSettingsIndexRoute =
  authenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedHelpCenterIndexRoute =
  authenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSettingsNotificationsRoute =
  authenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsDisplayRoute =
  authenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAppearanceRoute =
  authenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAccountRoute =
  authenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedMyNoobleShopRouteRoute =
  authenticatedMyNoobleShopRouteRouteImport.update({
    id: '/my-nooble/shop',
    path: '/my-nooble/shop',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedMyNoobleAgentsRouteRoute =
  authenticatedMyNoobleAgentsRouteRouteImport.update({
    id: '/my-nooble/agents',
    path: '/my-nooble/agents',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedMyNoobleShopIndexRoute =
  authenticatedMyNoobleShopIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedMyNoobleShopRouteRoute,
  } as any)
const authenticatedMyNoobleProfileIndexRoute =
  authenticatedMyNoobleProfileIndexRouteImport.update({
    id: '/my-nooble/profile/',
    path: '/my-nooble/profile/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedMyNoobleDesignIndexRoute =
  authenticatedMyNoobleDesignIndexRouteImport.update({
    id: '/my-nooble/design/',
    path: '/my-nooble/design/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedMyNoobleAgentsIndexRoute =
  authenticatedMyNoobleAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedMyNoobleAgentsRouteRoute,
  } as any)
const authenticatedInsightsProfileAnalyticsIndexRoute =
  authenticatedInsightsProfileAnalyticsIndexRouteImport.update({
    id: '/profile-analytics/',
    path: '/profile-analytics/',
    getParentRoute: () => authenticatedInsightsRouteRoute,
  } as any)
const authenticatedInsightsOverviewIndexRoute =
  authenticatedInsightsOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => authenticatedInsightsRouteRoute,
  } as any)
const authenticatedInsightsConversationFlowIndexRoute =
  authenticatedInsightsConversationFlowIndexRouteImport.update({
    id: '/conversation-flow/',
    path: '/conversation-flow/',
    getParentRoute: () => authenticatedInsightsRouteRoute,
  } as any)
const authenticatedMyNoobleShopOrdersIndexRoute =
  authenticatedMyNoobleShopOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => authenticatedMyNoobleShopRouteRoute,
  } as any)
const authenticatedMyNoobleShopMyProductsIndexRoute =
  authenticatedMyNoobleShopMyProductsIndexRouteImport.update({
    id: '/my-products/',
    path: '/my-products/',
    getParentRoute: () => authenticatedMyNoobleShopRouteRoute,
  } as any)
const authenticatedMyNoobleShopEditIndexRoute =
  authenticatedMyNoobleShopEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => authenticatedMyNoobleShopRouteRoute,
  } as any)
const authenticatedMyNoobleAgentsToolsIndexRoute =
  authenticatedMyNoobleAgentsToolsIndexRouteImport.update({
    id: '/tools/',
    path: '/tools/',
    getParentRoute: () => authenticatedMyNoobleAgentsRouteRoute,
  } as any)
const authenticatedMyNoobleAgentsKnowledgeIndexRoute =
  authenticatedMyNoobleAgentsKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => authenticatedMyNoobleAgentsRouteRoute,
  } as any)
const authenticatedMyNoobleAgentsAgentsIndexRoute =
  authenticatedMyNoobleAgentsAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => authenticatedMyNoobleAgentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexRoute
  '/$username': typeof UsernameRoute
  '/conversations': typeof authenticatedConversationsRouteRoute
  '/insights': typeof authenticatedInsightsRouteRouteWithChildren
  '/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/my-nooble/agents': typeof authenticatedMyNoobleAgentsRouteRouteWithChildren
  '/my-nooble/shop': typeof authenticatedMyNoobleShopRouteRouteWithChildren
  '/settings/account': typeof authenticatedSettingsAccountRoute
  '/settings/appearance': typeof authenticatedSettingsAppearanceRoute
  '/settings/display': typeof authenticatedSettingsDisplayRoute
  '/settings/notifications': typeof authenticatedSettingsNotificationsRoute
  '/help-center': typeof authenticatedHelpCenterIndexRoute
  '/settings/': typeof authenticatedSettingsIndexRoute
  '/insights/conversation-flow': typeof authenticatedInsightsConversationFlowIndexRoute
  '/insights/overview': typeof authenticatedInsightsOverviewIndexRoute
  '/insights/profile-analytics': typeof authenticatedInsightsProfileAnalyticsIndexRoute
  '/my-nooble/agents/': typeof authenticatedMyNoobleAgentsIndexRoute
  '/my-nooble/design': typeof authenticatedMyNoobleDesignIndexRoute
  '/my-nooble/profile': typeof authenticatedMyNoobleProfileIndexRoute
  '/my-nooble/shop/': typeof authenticatedMyNoobleShopIndexRoute
  '/my-nooble/agents/agents': typeof authenticatedMyNoobleAgentsAgentsIndexRoute
  '/my-nooble/agents/knowledge': typeof authenticatedMyNoobleAgentsKnowledgeIndexRoute
  '/my-nooble/agents/tools': typeof authenticatedMyNoobleAgentsToolsIndexRoute
  '/my-nooble/shop/edit': typeof authenticatedMyNoobleShopEditIndexRoute
  '/my-nooble/shop/my-products': typeof authenticatedMyNoobleShopMyProductsIndexRoute
  '/my-nooble/shop/orders': typeof authenticatedMyNoobleShopOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/$username': typeof UsernameRoute
  '/conversations': typeof authenticatedConversationsRouteRoute
  '/insights': typeof authenticatedInsightsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof authenticatedIndexRoute
  '/settings/account': typeof authenticatedSettingsAccountRoute
  '/settings/appearance': typeof authenticatedSettingsAppearanceRoute
  '/settings/display': typeof authenticatedSettingsDisplayRoute
  '/settings/notifications': typeof authenticatedSettingsNotificationsRoute
  '/help-center': typeof authenticatedHelpCenterIndexRoute
  '/settings': typeof authenticatedSettingsIndexRoute
  '/insights/conversation-flow': typeof authenticatedInsightsConversationFlowIndexRoute
  '/insights/overview': typeof authenticatedInsightsOverviewIndexRoute
  '/insights/profile-analytics': typeof authenticatedInsightsProfileAnalyticsIndexRoute
  '/my-nooble/agents': typeof authenticatedMyNoobleAgentsIndexRoute
  '/my-nooble/design': typeof authenticatedMyNoobleDesignIndexRoute
  '/my-nooble/profile': typeof authenticatedMyNoobleProfileIndexRoute
  '/my-nooble/shop': typeof authenticatedMyNoobleShopIndexRoute
  '/my-nooble/agents/agents': typeof authenticatedMyNoobleAgentsAgentsIndexRoute
  '/my-nooble/agents/knowledge': typeof authenticatedMyNoobleAgentsKnowledgeIndexRoute
  '/my-nooble/agents/tools': typeof authenticatedMyNoobleAgentsToolsIndexRoute
  '/my-nooble/shop/edit': typeof authenticatedMyNoobleShopEditIndexRoute
  '/my-nooble/shop/my-products': typeof authenticatedMyNoobleShopMyProductsIndexRoute
  '/my-nooble/shop/orders': typeof authenticatedMyNoobleShopOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/(authenticated)/conversations': typeof authenticatedConversationsRouteRoute
  '/(authenticated)/insights': typeof authenticatedInsightsRouteRouteWithChildren
  '/(authenticated)/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(authenticated)/my-nooble/agents': typeof authenticatedMyNoobleAgentsRouteRouteWithChildren
  '/(authenticated)/my-nooble/shop': typeof authenticatedMyNoobleShopRouteRouteWithChildren
  '/(authenticated)/settings/account': typeof authenticatedSettingsAccountRoute
  '/(authenticated)/settings/appearance': typeof authenticatedSettingsAppearanceRoute
  '/(authenticated)/settings/display': typeof authenticatedSettingsDisplayRoute
  '/(authenticated)/settings/notifications': typeof authenticatedSettingsNotificationsRoute
  '/(authenticated)/help-center/': typeof authenticatedHelpCenterIndexRoute
  '/(authenticated)/settings/': typeof authenticatedSettingsIndexRoute
  '/(authenticated)/insights/conversation-flow/': typeof authenticatedInsightsConversationFlowIndexRoute
  '/(authenticated)/insights/overview/': typeof authenticatedInsightsOverviewIndexRoute
  '/(authenticated)/insights/profile-analytics/': typeof authenticatedInsightsProfileAnalyticsIndexRoute
  '/(authenticated)/my-nooble/agents/': typeof authenticatedMyNoobleAgentsIndexRoute
  '/(authenticated)/my-nooble/design/': typeof authenticatedMyNoobleDesignIndexRoute
  '/(authenticated)/my-nooble/profile/': typeof authenticatedMyNoobleProfileIndexRoute
  '/(authenticated)/my-nooble/shop/': typeof authenticatedMyNoobleShopIndexRoute
  '/(authenticated)/my-nooble/agents/agents/': typeof authenticatedMyNoobleAgentsAgentsIndexRoute
  '/(authenticated)/my-nooble/agents/knowledge/': typeof authenticatedMyNoobleAgentsKnowledgeIndexRoute
  '/(authenticated)/my-nooble/agents/tools/': typeof authenticatedMyNoobleAgentsToolsIndexRoute
  '/(authenticated)/my-nooble/shop/edit/': typeof authenticatedMyNoobleShopEditIndexRoute
  '/(authenticated)/my-nooble/shop/my-products/': typeof authenticatedMyNoobleShopMyProductsIndexRoute
  '/(authenticated)/my-nooble/shop/orders/': typeof authenticatedMyNoobleShopOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/conversations'
    | '/insights'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/my-nooble/agents'
    | '/my-nooble/shop'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/help-center'
    | '/settings/'
    | '/insights/conversation-flow'
    | '/insights/overview'
    | '/insights/profile-analytics'
    | '/my-nooble/agents/'
    | '/my-nooble/design'
    | '/my-nooble/profile'
    | '/my-nooble/shop/'
    | '/my-nooble/agents/agents'
    | '/my-nooble/agents/knowledge'
    | '/my-nooble/agents/tools'
    | '/my-nooble/shop/edit'
    | '/my-nooble/shop/my-products'
    | '/my-nooble/shop/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$username'
    | '/conversations'
    | '/insights'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/help-center'
    | '/settings'
    | '/insights/conversation-flow'
    | '/insights/overview'
    | '/insights/profile-analytics'
    | '/my-nooble/agents'
    | '/my-nooble/design'
    | '/my-nooble/profile'
    | '/my-nooble/shop'
    | '/my-nooble/agents/agents'
    | '/my-nooble/agents/knowledge'
    | '/my-nooble/agents/tools'
    | '/my-nooble/shop/edit'
    | '/my-nooble/shop/my-products'
    | '/my-nooble/shop/orders'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/$username'
    | '/(authenticated)/conversations'
    | '/(authenticated)/insights'
    | '/(authenticated)/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(authenticated)/'
    | '/(authenticated)/my-nooble/agents'
    | '/(authenticated)/my-nooble/shop'
    | '/(authenticated)/settings/account'
    | '/(authenticated)/settings/appearance'
    | '/(authenticated)/settings/display'
    | '/(authenticated)/settings/notifications'
    | '/(authenticated)/help-center/'
    | '/(authenticated)/settings/'
    | '/(authenticated)/insights/conversation-flow/'
    | '/(authenticated)/insights/overview/'
    | '/(authenticated)/insights/profile-analytics/'
    | '/(authenticated)/my-nooble/agents/'
    | '/(authenticated)/my-nooble/design/'
    | '/(authenticated)/my-nooble/profile/'
    | '/(authenticated)/my-nooble/shop/'
    | '/(authenticated)/my-nooble/agents/agents/'
    | '/(authenticated)/my-nooble/agents/knowledge/'
    | '/(authenticated)/my-nooble/agents/tools/'
    | '/(authenticated)/my-nooble/shop/edit/'
    | '/(authenticated)/my-nooble/shop/my-products/'
    | '/(authenticated)/my-nooble/shop/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  UsernameRoute: typeof UsernameRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/settings': {
      id: '/(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authenticatedSettingsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/insights': {
      id: '/(authenticated)/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof authenticatedInsightsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/conversations': {
      id: '/(authenticated)/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof authenticatedConversationsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/settings/': {
      id: '/(authenticated)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof authenticatedSettingsIndexRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/help-center/': {
      id: '/(authenticated)/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof authenticatedHelpCenterIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/settings/notifications': {
      id: '/(authenticated)/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof authenticatedSettingsNotificationsRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/display': {
      id: '/(authenticated)/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof authenticatedSettingsDisplayRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/appearance': {
      id: '/(authenticated)/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof authenticatedSettingsAppearanceRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/account': {
      id: '/(authenticated)/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof authenticatedSettingsAccountRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/my-nooble/shop': {
      id: '/(authenticated)/my-nooble/shop'
      path: '/my-nooble/shop'
      fullPath: '/my-nooble/shop'
      preLoaderRoute: typeof authenticatedMyNoobleShopRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/my-nooble/agents': {
      id: '/(authenticated)/my-nooble/agents'
      path: '/my-nooble/agents'
      fullPath: '/my-nooble/agents'
      preLoaderRoute: typeof authenticatedMyNoobleAgentsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/my-nooble/shop/': {
      id: '/(authenticated)/my-nooble/shop/'
      path: '/'
      fullPath: '/my-nooble/shop/'
      preLoaderRoute: typeof authenticatedMyNoobleShopIndexRouteImport
      parentRoute: typeof authenticatedMyNoobleShopRouteRoute
    }
    '/(authenticated)/my-nooble/profile/': {
      id: '/(authenticated)/my-nooble/profile/'
      path: '/my-nooble/profile'
      fullPath: '/my-nooble/profile'
      preLoaderRoute: typeof authenticatedMyNoobleProfileIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/my-nooble/design/': {
      id: '/(authenticated)/my-nooble/design/'
      path: '/my-nooble/design'
      fullPath: '/my-nooble/design'
      preLoaderRoute: typeof authenticatedMyNoobleDesignIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/my-nooble/agents/': {
      id: '/(authenticated)/my-nooble/agents/'
      path: '/'
      fullPath: '/my-nooble/agents/'
      preLoaderRoute: typeof authenticatedMyNoobleAgentsIndexRouteImport
      parentRoute: typeof authenticatedMyNoobleAgentsRouteRoute
    }
    '/(authenticated)/insights/profile-analytics/': {
      id: '/(authenticated)/insights/profile-analytics/'
      path: '/profile-analytics'
      fullPath: '/insights/profile-analytics'
      preLoaderRoute: typeof authenticatedInsightsProfileAnalyticsIndexRouteImport
      parentRoute: typeof authenticatedInsightsRouteRoute
    }
    '/(authenticated)/insights/overview/': {
      id: '/(authenticated)/insights/overview/'
      path: '/overview'
      fullPath: '/insights/overview'
      preLoaderRoute: typeof authenticatedInsightsOverviewIndexRouteImport
      parentRoute: typeof authenticatedInsightsRouteRoute
    }
    '/(authenticated)/insights/conversation-flow/': {
      id: '/(authenticated)/insights/conversation-flow/'
      path: '/conversation-flow'
      fullPath: '/insights/conversation-flow'
      preLoaderRoute: typeof authenticatedInsightsConversationFlowIndexRouteImport
      parentRoute: typeof authenticatedInsightsRouteRoute
    }
    '/(authenticated)/my-nooble/shop/orders/': {
      id: '/(authenticated)/my-nooble/shop/orders/'
      path: '/orders'
      fullPath: '/my-nooble/shop/orders'
      preLoaderRoute: typeof authenticatedMyNoobleShopOrdersIndexRouteImport
      parentRoute: typeof authenticatedMyNoobleShopRouteRoute
    }
    '/(authenticated)/my-nooble/shop/my-products/': {
      id: '/(authenticated)/my-nooble/shop/my-products/'
      path: '/my-products'
      fullPath: '/my-nooble/shop/my-products'
      preLoaderRoute: typeof authenticatedMyNoobleShopMyProductsIndexRouteImport
      parentRoute: typeof authenticatedMyNoobleShopRouteRoute
    }
    '/(authenticated)/my-nooble/shop/edit/': {
      id: '/(authenticated)/my-nooble/shop/edit/'
      path: '/edit'
      fullPath: '/my-nooble/shop/edit'
      preLoaderRoute: typeof authenticatedMyNoobleShopEditIndexRouteImport
      parentRoute: typeof authenticatedMyNoobleShopRouteRoute
    }
    '/(authenticated)/my-nooble/agents/tools/': {
      id: '/(authenticated)/my-nooble/agents/tools/'
      path: '/tools'
      fullPath: '/my-nooble/agents/tools'
      preLoaderRoute: typeof authenticatedMyNoobleAgentsToolsIndexRouteImport
      parentRoute: typeof authenticatedMyNoobleAgentsRouteRoute
    }
    '/(authenticated)/my-nooble/agents/knowledge/': {
      id: '/(authenticated)/my-nooble/agents/knowledge/'
      path: '/knowledge'
      fullPath: '/my-nooble/agents/knowledge'
      preLoaderRoute: typeof authenticatedMyNoobleAgentsKnowledgeIndexRouteImport
      parentRoute: typeof authenticatedMyNoobleAgentsRouteRoute
    }
    '/(authenticated)/my-nooble/agents/agents/': {
      id: '/(authenticated)/my-nooble/agents/agents/'
      path: '/agents'
      fullPath: '/my-nooble/agents/agents'
      preLoaderRoute: typeof authenticatedMyNoobleAgentsAgentsIndexRouteImport
      parentRoute: typeof authenticatedMyNoobleAgentsRouteRoute
    }
  }
}

interface authenticatedInsightsRouteRouteChildren {
  authenticatedInsightsConversationFlowIndexRoute: typeof authenticatedInsightsConversationFlowIndexRoute
  authenticatedInsightsOverviewIndexRoute: typeof authenticatedInsightsOverviewIndexRoute
  authenticatedInsightsProfileAnalyticsIndexRoute: typeof authenticatedInsightsProfileAnalyticsIndexRoute
}

const authenticatedInsightsRouteRouteChildren: authenticatedInsightsRouteRouteChildren =
  {
    authenticatedInsightsConversationFlowIndexRoute:
      authenticatedInsightsConversationFlowIndexRoute,
    authenticatedInsightsOverviewIndexRoute:
      authenticatedInsightsOverviewIndexRoute,
    authenticatedInsightsProfileAnalyticsIndexRoute:
      authenticatedInsightsProfileAnalyticsIndexRoute,
  }

const authenticatedInsightsRouteRouteWithChildren =
  authenticatedInsightsRouteRoute._addFileChildren(
    authenticatedInsightsRouteRouteChildren,
  )

interface authenticatedSettingsRouteRouteChildren {
  authenticatedSettingsAccountRoute: typeof authenticatedSettingsAccountRoute
  authenticatedSettingsAppearanceRoute: typeof authenticatedSettingsAppearanceRoute
  authenticatedSettingsDisplayRoute: typeof authenticatedSettingsDisplayRoute
  authenticatedSettingsNotificationsRoute: typeof authenticatedSettingsNotificationsRoute
  authenticatedSettingsIndexRoute: typeof authenticatedSettingsIndexRoute
}

const authenticatedSettingsRouteRouteChildren: authenticatedSettingsRouteRouteChildren =
  {
    authenticatedSettingsAccountRoute: authenticatedSettingsAccountRoute,
    authenticatedSettingsAppearanceRoute: authenticatedSettingsAppearanceRoute,
    authenticatedSettingsDisplayRoute: authenticatedSettingsDisplayRoute,
    authenticatedSettingsNotificationsRoute:
      authenticatedSettingsNotificationsRoute,
    authenticatedSettingsIndexRoute: authenticatedSettingsIndexRoute,
  }

const authenticatedSettingsRouteRouteWithChildren =
  authenticatedSettingsRouteRoute._addFileChildren(
    authenticatedSettingsRouteRouteChildren,
  )

interface authenticatedMyNoobleAgentsRouteRouteChildren {
  authenticatedMyNoobleAgentsIndexRoute: typeof authenticatedMyNoobleAgentsIndexRoute
  authenticatedMyNoobleAgentsAgentsIndexRoute: typeof authenticatedMyNoobleAgentsAgentsIndexRoute
  authenticatedMyNoobleAgentsKnowledgeIndexRoute: typeof authenticatedMyNoobleAgentsKnowledgeIndexRoute
  authenticatedMyNoobleAgentsToolsIndexRoute: typeof authenticatedMyNoobleAgentsToolsIndexRoute
}

const authenticatedMyNoobleAgentsRouteRouteChildren: authenticatedMyNoobleAgentsRouteRouteChildren =
  {
    authenticatedMyNoobleAgentsIndexRoute:
      authenticatedMyNoobleAgentsIndexRoute,
    authenticatedMyNoobleAgentsAgentsIndexRoute:
      authenticatedMyNoobleAgentsAgentsIndexRoute,
    authenticatedMyNoobleAgentsKnowledgeIndexRoute:
      authenticatedMyNoobleAgentsKnowledgeIndexRoute,
    authenticatedMyNoobleAgentsToolsIndexRoute:
      authenticatedMyNoobleAgentsToolsIndexRoute,
  }

const authenticatedMyNoobleAgentsRouteRouteWithChildren =
  authenticatedMyNoobleAgentsRouteRoute._addFileChildren(
    authenticatedMyNoobleAgentsRouteRouteChildren,
  )

interface authenticatedMyNoobleShopRouteRouteChildren {
  authenticatedMyNoobleShopIndexRoute: typeof authenticatedMyNoobleShopIndexRoute
  authenticatedMyNoobleShopEditIndexRoute: typeof authenticatedMyNoobleShopEditIndexRoute
  authenticatedMyNoobleShopMyProductsIndexRoute: typeof authenticatedMyNoobleShopMyProductsIndexRoute
  authenticatedMyNoobleShopOrdersIndexRoute: typeof authenticatedMyNoobleShopOrdersIndexRoute
}

const authenticatedMyNoobleShopRouteRouteChildren: authenticatedMyNoobleShopRouteRouteChildren =
  {
    authenticatedMyNoobleShopIndexRoute: authenticatedMyNoobleShopIndexRoute,
    authenticatedMyNoobleShopEditIndexRoute:
      authenticatedMyNoobleShopEditIndexRoute,
    authenticatedMyNoobleShopMyProductsIndexRoute:
      authenticatedMyNoobleShopMyProductsIndexRoute,
    authenticatedMyNoobleShopOrdersIndexRoute:
      authenticatedMyNoobleShopOrdersIndexRoute,
  }

const authenticatedMyNoobleShopRouteRouteWithChildren =
  authenticatedMyNoobleShopRouteRoute._addFileChildren(
    authenticatedMyNoobleShopRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedConversationsRouteRoute: typeof authenticatedConversationsRouteRoute
  authenticatedInsightsRouteRoute: typeof authenticatedInsightsRouteRouteWithChildren
  authenticatedSettingsRouteRoute: typeof authenticatedSettingsRouteRouteWithChildren
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedMyNoobleAgentsRouteRoute: typeof authenticatedMyNoobleAgentsRouteRouteWithChildren
  authenticatedMyNoobleShopRouteRoute: typeof authenticatedMyNoobleShopRouteRouteWithChildren
  authenticatedHelpCenterIndexRoute: typeof authenticatedHelpCenterIndexRoute
  authenticatedMyNoobleDesignIndexRoute: typeof authenticatedMyNoobleDesignIndexRoute
  authenticatedMyNoobleProfileIndexRoute: typeof authenticatedMyNoobleProfileIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedConversationsRouteRoute: authenticatedConversationsRouteRoute,
  authenticatedInsightsRouteRoute: authenticatedInsightsRouteRouteWithChildren,
  authenticatedSettingsRouteRoute: authenticatedSettingsRouteRouteWithChildren,
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedMyNoobleAgentsRouteRoute:
    authenticatedMyNoobleAgentsRouteRouteWithChildren,
  authenticatedMyNoobleShopRouteRoute:
    authenticatedMyNoobleShopRouteRouteWithChildren,
  authenticatedHelpCenterIndexRoute: authenticatedHelpCenterIndexRoute,
  authenticatedMyNoobleDesignIndexRoute: authenticatedMyNoobleDesignIndexRoute,
  authenticatedMyNoobleProfileIndexRoute:
    authenticatedMyNoobleProfileIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  UsernameRoute: UsernameRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
